[package]
name = "ourcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "*"
rand = "*"
itertools = "*"
vpsearch = "*"
csv = "*"
colorsys = "*"
anyhow = "*"
intbits = "*"
serde = "*"
leafwing-input-manager = "*"
strum = "*"
strum_macros = "*"
dashmap = "*"
futures-lite = "*"
array-macro = "*"
noise = "*"

[profile.test]
opt-level = 3
