[package]
name = "ourcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.12" }
bevy_atmosphere = "0.8"
leafwing-input-manager = "*"
rand = "*"
indexmap = "*"
itertools = "*"
vpsearch = "*"
parking_lot = "*"
crossbeam = "*"
csv = "*"
colorsys = "*"
anyhow = "*"
serde = "*"
strum = "*"
strum_macros = "*"
dashmap = "*"
futures-lite = "*"
array-macro = "*"
packed-uints = "*"
block-mesh = "*"
lazy_static = "*"
noise-algebra = { git = "https://github.com/Inspirateur/noise-algebra" }
nd-interval = { git = "https://github.com/Inspirateur/nd-interval" }

[profile.dev]
opt-level = 1
