[package]
name = "ourcraft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "*"
rand = "*"
itertools = "*"
vpsearch = "*"
csv = "*"
colorsys = "*"
anyhow = "*"
serde = "*"
leafwing-input-manager = "*"
strum = "*"
strum_macros = "*"
dashmap = "*"
futures-lite = "*"
array-macro = "*"
packed-uints = "*"
noise-algebra = { git = "https://github.com/Inspirateur/noise-algebra" }
nd-interval = { git = "https://github.com/Inspirateur/nd-interval" }

[profile.test]
opt-level = 3

[dev-dependencies]
criterion = "*"

[[bench]]
name = "chunk"
harness = false